version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    ports:
      - 8501:8501
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - /errors-management-system:/data/db
    
